/* Generated By:JavaCC: Do not edit this line. HtmlParserConstants.java */
package com.quiotix.html.parser;

public interface HtmlParserConstants {

  int EOF = 0;
  int ALPHA_CHAR = 1;
  int NUM_CHAR = 2;
  int ALPHANUM_CHAR = 3;
  int IDENTIFIER_CHAR = 4;
  int IDENTIFIER = 5;
  int QUOTED_STRING_NB = 6;
  int QUOTED_STRING = 7;
  int WHITESPACE = 8;
  int NEWLINE = 9;
  int QUOTE = 10;
  int EOL = 11;
  int TAG_START = 12;
  int ENDTAG_START = 13;
  int COMMENT_START = 14;
  int DECL_START = 15;
  int PCDATA = 16;
  int TAG_SCRIPT = 17;
  int TAG_STYLE = 18;
  int TAG_NAME = 19;
  int LST_ERROR = 20;
  int ATTR_NAME = 22;
  int TAG_END = 23;
  int TAG_SLASHEND = 24;
  int ATTR_EQ = 25;
  int IMPLICIT_TAG_END = 26;
  int LIT_ERROR = 27;
  int ATTR_VAL = 29;
  int LAV_ERROR = 30;
  int COMMENT_END = 31;
  int DASH = 32;
  int COMMENT_EOL = 33;
  int COMMENT_WORD = 34;
  int DECL_ANY = 35;
  int DECL_END = 36;
  int SCRIPT_END = 37;
  int STYLE_END = 38;
  int BLOCK_EOL = 39;
  int BLOCK_LBR = 40;
  int BLOCK_WORD = 41;

  int LexStyle = 0;
  int LexScript = 1;
  int LexDecl = 2;
  int LexComment = 3;
  int LexAttrVal = 4;
  int LexInTag = 5;
  int LexStartTag = 6;
  int DEFAULT = 7;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING_NB>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<QUOTE>",
    "<EOL>",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "\"<!\"",
    "<PCDATA>",
    "\"SCRIPT\"",
    "\"STYLE\"",
    "<TAG_NAME>",
    "<LST_ERROR>",
    "<token of kind 21>",
    "<ATTR_NAME>",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "\"<\"",
    "<LIT_ERROR>",
    "<token of kind 28>",
    "<ATTR_VAL>",
    "<LAV_ERROR>",
    "<COMMENT_END>",
    "\"-\"",
    "<COMMENT_EOL>",
    "<COMMENT_WORD>",
    "<DECL_ANY>",
    "\">\"",
    "\"</SCRIPT>\"",
    "\"</STYLE>\"",
    "<BLOCK_EOL>",
    "\"<\"",
    "<BLOCK_WORD>",
  };

}
