/* Generated By:JavaCC: Do not edit this line. HtmlParserConstants.java */
package com.quiotix.html.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 4;
  /** RegularExpression Id. */
  int NUM_CHAR = 5;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 6;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int QUOTED_STRING_NB = 9;
  /** RegularExpression Id. */
  int QUOTED_STRING = 10;
  /** RegularExpression Id. */
  int WHITESPACE = 11;
  /** RegularExpression Id. */
  int NEWLINE = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int TAG_START = 15;
  /** RegularExpression Id. */
  int ENDTAG_START = 16;
  /** RegularExpression Id. */
  int COMMENT_START = 17;
  /** RegularExpression Id. */
  int DECL_START = 18;
  /** RegularExpression Id. */
  int PCDATA = 19;
  /** RegularExpression Id. */
  int TAG_SCRIPT = 20;
  /** RegularExpression Id. */
  int TAG_STYLE = 21;
  /** RegularExpression Id. */
  int TAG_NAME = 22;
  /** RegularExpression Id. */
  int LST_ERROR = 23;
  /** RegularExpression Id. */
  int ATTR_NAME = 25;
  /** RegularExpression Id. */
  int TAG_END = 26;
  /** RegularExpression Id. */
  int TAG_SLASHEND = 27;
  /** RegularExpression Id. */
  int ATTR_EQ = 28;
  /** RegularExpression Id. */
  int IMPLICIT_TAG_END = 29;
  /** RegularExpression Id. */
  int LIT_ERROR = 30;
  /** RegularExpression Id. */
  int ATTR_VAL = 32;
  /** RegularExpression Id. */
  int LAV_ERROR = 33;
  /** RegularExpression Id. */
  int COMMENT_END = 34;
  /** RegularExpression Id. */
  int DASH = 35;
  /** RegularExpression Id. */
  int COMMENT_EOL = 36;
  /** RegularExpression Id. */
  int COMMENT_WORD = 37;
  /** RegularExpression Id. */
  int DECL_ANY = 38;
  /** RegularExpression Id. */
  int DECL_END = 39;
  /** RegularExpression Id. */
  int SCRIPT_END = 40;
  /** RegularExpression Id. */
  int STYLE_END = 41;
  /** RegularExpression Id. */
  int BLOCK_EOL = 42;
  /** RegularExpression Id. */
  int BLOCK_LBR = 43;
  /** RegularExpression Id. */
  int BLOCK_WORD = 44;

  /** Lexical state. */
  int LexStyle = 0;
  /** Lexical state. */
  int LexScript = 1;
  /** Lexical state. */
  int LexDecl = 2;
  /** Lexical state. */
  int LexComment = 3;
  /** Lexical state. */
  int LexAttrVal = 4;
  /** Lexical state. */
  int LexInTag = 5;
  /** Lexical state. */
  int LexStartTag = 6;
  /** Lexical state. */
  int DEFAULT = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\\n\"",
    "\"=\\r\\n\"",
    "\"=\\r\"",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING_NB>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<QUOTE>",
    "<EOL>",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "\"<!\"",
    "<PCDATA>",
    "\"SCRIPT\"",
    "\"STYLE\"",
    "<TAG_NAME>",
    "<LST_ERROR>",
    "<token of kind 24>",
    "<ATTR_NAME>",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "\"<\"",
    "<LIT_ERROR>",
    "<token of kind 31>",
    "<ATTR_VAL>",
    "<LAV_ERROR>",
    "<COMMENT_END>",
    "\"-\"",
    "<COMMENT_EOL>",
    "<COMMENT_WORD>",
    "<DECL_ANY>",
    "\">\"",
    "\"</SCRIPT>\"",
    "\"</STYLE>\"",
    "<BLOCK_EOL>",
    "\"<\"",
    "<BLOCK_WORD>",
  };

}
